 # Setup
title: 'NTU MSBA'
url: https://ntumsba.github.io/MSBA-public-2020/

# Settings
theme: jekyll-theme-midnight
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true

collections:
  '2019':
    output: true
  '2020':
    output: true

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor